export const fEntries = [
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
  {
    module: "DRE",
    id: "DRE-124",
    titulo: "Título do registro",
    value: "Valor do registro",
    type: "Tipo do registro",
    family: "Família",
    group: "Grupo",
    reporter: {
      name: "Nome sobrenome",
    },
    date: "Seg, 15/06 - 15:00",
  },
]
