export const SettRegOptions = {
  sex: [
    { key: "ma", value: "Masculino" },
    { key: "fm", value: "Feminino" },
  ],
  civState: [
    { key: "00", value: "Solteiro" },
    { key: "01", value: "Casado" },
    { key: "02", value: "Divorciado" },
    { key: "03", value: "Viúvo" },
    { key: "04", value: "Separado judicialmente" },
  ],
  state: [
    { key: "ac", value: "Acre" },
    { key: "al", value: "Alagoas" },
    { key: "ap", value: "Amapá" },
    { key: "am", value: "Amazonas" },
    { key: "ba", value: "Bahia" },
    { key: "ce", value: "Ceará" },
    { key: "df", value: "Distrito Federal" },
    { key: "es", value: "Espírito Santo" },
    { key: "go", value: "Goiás" },
    { key: "ma", value: "Maranhão" },
    { key: "mt", value: "Mato Grosso" },
    { key: "ms", value: "Mato Grosso do Sul" },
    { key: "mg", value: "Minas Gerais" },
    { key: "pa", value: "Pará" },
    { key: "pb", value: "Paraíba" },
    { key: "pr", value: "Paraná" },
    { key: "pe", value: "Pernambuco" },
    { key: "pi", value: "Piauí" },
    { key: "rj", value: "Rio de Janeiro" },
    { key: "rn", value: "Rio Grande do Norte" },
    { key: "rs", value: "Rio Grande do Sul" },
    { key: "ro", value: "Rondônia" },
    { key: "rr", value: "Roraima" },
    { key: "sc", value: "Santa Catarina" },
    { key: "sp", value: "São Paulo" },
    { key: "se", value: "Sergipe" },
    { key: "to", value: "Tocantins" },
  ],
  country: [
    { key: "br", value: "Brasil" },
    { key: "ar", value: "Argentina" },
    { key: "eu", value: "Estados Unidos" },
  ],
} as const

export const SettRegOptionsRO = { ...SettRegOptions }
